### ISSUE TITLE
cannot run Scmlpick using SeisComP version 7

### ISSUE THREAD

**Issue by Donavin97** [ut-beg-texnet/scmlpick#1]
Good day,
I am very pplease that an opensource ML picker is being integrated into SeisComP.
I am having some trouble getting the module to work propperly.
1. When trying to run the module using the command line, by running scmlpick --debug, I get errors that time formatting cannot be used propperly.
I suspect that this has to do with trying to use seiscomp::time::gmt and obspy UtcDateTime together.
I unfortunately cannot downgrade my seiscomp version, as this is a production system.
Thanks for the great work.
Best:
Donavin.

**Comment by Camilo-sismo** [comment]
Hi Donavin,

Thanks for letting me know. I will update my test system to SeisComP 7 to see if I experience the same issue as you.
In the meantime, please let me know if you have had a chance to test the module on another server running SeisComP 6.

Cheers,
Camilo

**Comment by Camilo-sismo** [comment]
Hi Donavin,

I ran my tests and observed the same issue. I’ve fixed it and pushed the changes to the main branch.
Please let me know if it works for you.

Cheers,
Camilo

**Comment by Donavin97** [comment]
Good day,
I pulled the updated code.
The time issue seems to be resolved.
However, scmlpick still failes to read records from the recordstream and mseed files.
I am using seiscomp version 7.0.3.
When I run scmlpick in real time I get the following message:
```
2026/01/21 12:33:14 [debug/log] No data available in record.
```
Also at the beginning of the excecution this line appears multiple times:
```
2026/01/21 12:32:13 [warning/SDS] ... has invalid time window -> ignore this request above
```
Any help or insite would be appreciated.
From my understanding, it seems that the record stream failes to parse times correctly.
I do program a lot using the SeisComp API, but my understanding of the recordstream interface is limited.
I will try and fiddle around on my side, and if I manage a fix I will create a PR if that will be okay with you?
Best:
Donavin.

FYI: When running a playback, the data seems to be picked, but the pick file is empty, and the worker_*.log files remain empty as well.

**Comment by Camilo-sismo** [comment]
Hi Donavin,

Let me review this new version in more detail. It seems to be running fine on my side, but I am seeing some false picks that I did not observe in the last stable version. I will investigate this further, and after testing, I will push a new stable version compatible with SeisComP 7.

Of course, PRs are welcome.

Cheers,
Camilo

**Comment by Camilo-sismo** [comment]
Hi Donavin,

I found the issue that was producing false picks in the latest version, and it has now been fixed. I am currently using the version from the main branch in my SeisComP 7 installation, and it is working well, producing good quality results with no recordstream errors.

Please update your installation and make sure to also update the predictor to the latest version. Let me know if you are still experiencing any issues.

Also, remember to:

Configure your recordstream to receive real-time data
Set up the proper bindings for scmlpick
Configure the corresponding profiles in the module settings

I’m very interested in your test, so feel free to reach out if you’d like to schedule a short meeting.

Cheers,
Camilo

**Comment by Donavin97** [comment]
Hi there Camilo,
Thanks very much for your efforts.
I can confirm that the picker works in realtime mode.
However I see that it is still having trouble in playback mode.
I try to run an mseed file through the picker.
I can see the cpu working, but there are no picks written to the output xml file."
There are no errors thrown, even in debug mode.
The command I run is as follows:
```
scmlpick --profile DBW --playback --start "2026-01-20 15:00:00" --end "2026-01-20 16:00:00" --mseed-files file.mseed --output-file picks.xml --debug
```
My profile is set up correctly and also the bindings.
The picks.xml file contain only 4 lines as follows:
```
<?xml version="1.0" encoding="UTF-8"?>
<seiscomp xmlns="http://geofon.gfz.de/ns/seiscomp-schema/0.14" version="0.14">
  <EventParameters/>
</seiscomp>
```
Sorry, I know I am raising a lot of issues, but I really like this project and its potential.
Thanks.

**Comment by Camilo-sismo** [comment]
Hi Donavin,

I just ran a playback test using the latest version, and it is working fine on my end. Below is the command I am using:

scmlpick --playback --profile DELC --mseed-files data.mseed \
         --start "2026-01-21 18:24:00" --end "2026-01-21 18:27:00" \
         --output-file picks.xml -u playback --debug

The only difference I noticed compared to your command is the user parameter, which must be unique in order to establish a proper connection to the database. In my case, I am using -u playback. When I remove the user option, it throws a database connection related error.

Please also make sure that the profile you are using matches the one defined in the bindings for the stations contained in your MiniSEED file. Also, double-check that the start and end times are correct.

When running with the --debug option, you should see log lines similar to the following:

...
19:55:44 [debug] [2026-01-21 19:55:44.356250] 1 time chunk from 2026-01-21T18:24:00.000000Z to 2026-01-21T18:27:00.000000Z (single window).
19:55:46 [info] Allocates 56 amount of CPUs for the function of creating tasks with ray
19:56:13 [info] {'trace_name': 'TX.PB29.00.HHZ', 'network_name': '0 ', 'station_name': 'PB29', 'instrument_type': '0 ', 'station_lat': 0, 'station_lon': 0, 'station_elv': 0, 'PdateTime': datetime.datetime(2026, 1, 21, 18, 24, 48, 500000), 'p_prob': 0.928, 'SdateTime': datetime.datetime(2026, 1, 21, 18, 24, 50, 50000), 's_prob': 0.838}
19:56:13 [debug] Pick produced by EQCCT TX.PB29
19:56:13 [debug] <seiscomp.datamodel.Pick; proxy of <Swig Object of type 'Seiscomp::DataModel::Pick *' at 0x7f2d4872f960>>
19:56:13 [debug] Pick produced by EQCCT TX.PB29
...


I will continue running additional tests, but so far everything looks good on my side, both for real-time and playback executions.

Cheers,
Camilo

**Comment by Donavin97** [comment]
Good day Camilo,
I have figured out my problem.
It looks like my tensorflow version might be the issue.

When I create a virtual environment with python3.10 the code works fine.
However when running the code on my python3.12 main system the code doesn't execute, it looks like the tensorflow moddel cannot run.
When in the python3.10 environment, cpu usage is at 100 percent, but in the python3.12 environment, the CPU is between 20 and 60 percent.
I will test a bit more and see how this can be fixed.
Best:
Donavin.

**Comment by Donavin97** [comment]
Hi Camilo,
I am pleased to announse that my issues are fixed.
Upgrading to Tensorflow 2.20 has fixed the model errors.
Everything is working great!
Can't wait to see further developements to this module.
This would greatly improve earthquake detection in South Africa.
Thanks again for providing this module at no cost.
Think we can close the issue now, if anything else develops, I'll be sure to let you know.
Best:
Donavin.

**Comment by Camilo-sismo** [comment]
Hi Donavin,

It’s good to hear that the module is working well for you.
Please see a few comments below:

- CPU usage

Yes, you can use CPUs. At the moment, the module is designed to run in real time using a 60-second window (eqcct.windowLength). You can control the overlap between windows using eqcct.timeShift (default: 30 s). This means that, by default, you have 30 seconds to process each one-minute window. You need to find an appropriate balance between the number of stations and the number of CPUs to keep up with real-time processing. If you start noticing increasing pick delays, it is likely because you are processing too many stations with the available CPUs.

- Controlling the number of CPUs

Please control the number of CPUs using ray.numWorkers (CPUs used to prepare the data) and ray.numCPUs (CPUs used to process the data). As a reference, at TexNet we need at least 25 cores to process more than 700 channels in real time, although this strongly depends on the server specifications.

- Restricting which CPUs are used

If you want to control which CPU cores are available for processing, please modify
/SEISCOMP_ROOT/bin/scmlpick.
Near the end of the file, you will find:

core_mappings = {
    # "scmlpick": list(range(4, 25))
    script_name: list(range(num_cores))
}


Uncomment the line starting with "scmlpick" and comment out the line starting with script_name. Then adjust the values according to your server. For example, using "scmlpick": list(range(2, 27)), ray.numWorkers = 2, and ray.numCPUs = 25 will use the first 2 cores for data preparation and the next 25 cores for data processing. This way, Ray will be restricted to those cores; otherwise, it tends to use all available cores.

- Citations

Finally, if you use any results from this module in publications, please cite this GitHub repository or the paper (once it is published). This helps give more visibility to the module.

Cheers,
Camilo

**Comment by Donavin97** [comment]
Good day Camilo,
Thanks for your very detailed explanations.
I have applyed the CPU settings you suggested, going to test with a batch of data.
One thing that I do notice, is with the time constraint values, only chunks of 1 hour work.
If I want to process data around an event, lets say 5 minutes, the process exits.
I am not exactly sure why though, just wanted to bring this to your attention.
Best:
Donavin.
PS: Keep up this awesome module, I wonder if there will be any other modules released, like fault propperties, moment tensors, or other modules for SeisComP?

**Comment by Donavin97** [comment]
Hi again Camilo,
I just tested the picker again.
Everything works now, including time windows.
Please disregard my comment above about the time windows smaller than 1 hour not working, it seems to be fine now.
Thanks:
Donavin.
